### ISSUE TITLE
Gif image running flashing

### ISSUE THREAD

**Issue by ychong996** [koral--/android-gif-drawable#744] opened 2020-08-10 02:41 UTC
When I run GIF on my android 6.0, the GIT image keeps flashing

**Comment by koral--** [comment] 2020-08-14 18:13
Could you attach that GIF here? Or send it me by e-mail if it is not public?

**Comment by Leoand8** [comment] 2020-08-21 09:29
在安卓7.1.1系统上也会闪烁。而且我发现，从1.2.12版本开始会闪烁，小于这个版本的不会闪烁。Gif文件已发送到您的邮箱。
It also flashes on Android 7.1.1.
And I found that, starting with version 1.2.12, it would flash, and less than this version would not. The GIF file has been sent to your mailbox.

**Comment by koral--** [comment] 2020-08-24 01:23
Thanks I've received it. Will investigate issue soon.

**Comment by sihua007** [comment] 2020-09-05 09:08
> 在安卓7.1.1系统上也会闪烁。而且我发现，从1.2.12版本开始会闪烁，小于这个版本的不会闪烁。Gif文件已发送到您的邮箱。
> It also flashes on Android 7.1.1.
> And I found that, starting with version 1.2.12, it would flash, and less than this version would not. The GIF file has been sent to your mailbox.

你好，您说的小于1.2.12版本的不会闪烁，您试过哪个版本是OK的呢。因为我这边目前试了11和其他几个版本还是会闪烁的

**Comment by Leoand8** [comment] 2020-09-10 00:37
> 
> 
> > 在安卓7.1.1系统上也会闪烁。而且我发现，从1.2.12版本开始会闪烁，小于这个版本的不会闪烁。Gif文件已发送到您的邮箱。
> > It also flashes on Android 7.1.1.
> > And I found that, starting with version 1.2.12, it would flash, and less than this version would not. The GIF file has been sent to your mailbox.
> 
> 你好，您说的小于1.2.12版本的不会闪烁，您试过哪个版本是OK的呢。因为我这边目前试了11和其他几个版本还是会闪烁的

我试的1.2.11版本在我使用的几种手机和平板上不会闪烁。如小米8、华为Mate20、联想平板等，可能不同设备之间会存在某些差异。

**Comment by koral--** [comment] 2020-10-04 00:18
Sorry for the delay.
I was unable to reproduce this issue od few devices.
It looks like the same as https://github.com/koral--/android-gif-drawable/issues/604, check also https://github.com/koral--/android-gif-drawable/issues/162#issuecomment-99172799

For now I don't have any idea how this can be improved, so I'll close this ticket.
Feel free to submit a PR if you find some concrete solution.

Workaround is to not use drawable but eg. GifTextureView or GifTexImage2D.

**Closed as completed by koral--** 2020-10-04 00:18 UTC
Labels: bug
