### ISSUE TITLE
java.lang.VerifyError: pl/droidsonroids/gif/GifInfoHandle

### ISSUE THREAD

**Issue by xiaohua717** [koral--/android-gif-drawable#571] opened 2018-07-16 09:50 UTC
When I run your source code and demo, I get an error..
exeception in android version 4.4.2
ok in android version 5.1

FATAL EXCEPTION: main
                  Process: pl.droidsonroids.gif.sample, PID: 1995
                  java.lang.VerifyError: pl/droidsonroids/gif/GifInfoHandle
                      at pl.droidsonroids.gif.InputSource$AssetSource.open(InputSource.java:159)
                      at pl.droidsonroids.gif.InputSource.createHandleWith(InputSource.java:36)
                      at pl.droidsonroids.gif.InputSource.build(InputSource.java:32)
                      at pl.droidsonroids.gif.GifDrawableInit.build(GifDrawableInit.java:64)
                      at pl.droidsonroids.gif.sample.sources.GifSourcesAdapter.onBindViewHolder(GifSourcesAdapter.kt:30)
                      at pl.droidsonroids.gif.sample.sources.GifSourcesAdapter.onBindViewHolder(GifSourcesAdapter.kt:13)
                      at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
                      at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
                      at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
                      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                      at android.view.View.layout(View.java:14817)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2006)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1763)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1019)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5691)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                      at android.view.Choreographer.doFrame(Choreographer.java:544)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by koral--** [comment] 2018-07-16 10:05
Duplicate of https://github.com/koral--/android-gif-drawable/issues/570

**Closed by koral--** 2018-07-16 10:05 UTC
Labels: duplicate
