### ISSUE TITLE
Hi im moein Thankyou for your answer and library ihave a problem when i open the app the gif is start and after the second it stopped 

### ISSUE THREAD

**Issue by moeintav** [koral--/android-gif-drawable#369] opened 2016-12-30 22:26 UTC

**Comment by moeintav** [comment] 2016-12-30 22:27
Hi im moein Thankyou for your answer and library ihave a problem when i open the app the gif is start and after the second it stopped

**Comment by koral--** [comment] 2016-12-31 02:11
Duplicate of #370

**Closed by koral--** 2016-12-31 02:11 UTC
Labels: duplicate
