### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.app.my_app_package_name/app_lib/libpl_droidsonroids_gif.so" is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by RishabhSRS** [koral--/android-gif-drawable#815] opened 2022-12-23 12:26 UTC
Hello @koral-- 
I am facing this crash , can you please guide me how to fix it ?

Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.app.my_app_package_name/app_lib/libpl_droidsonroids_gif.so" is 64-bit instead of 32-bit
       at java.lang.Runtime.load0(Runtime.java:929)
       at java.lang.System.load(System.java:1625)
       at pl.droidsonroids.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
       at pl.droidsonroids.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:204)
       at pl.droidsonroids.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at pl.droidsonroids.relinker.ReLinker.loadLibrary(ReLinker.java:51)
       at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:52)
       at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:27)
       at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:161)
       at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:96)

**Comment by koral--** [comment] 2022-12-23 12:49
Please attach a project which reproduces this issue and tell on which device and Android version you are testing on.

**Comment by RishabhSRS** [comment] 2022-12-26 05:47
Device Name - Samsung Galaxy S10+ 
Android Version - 10 (Q)

**Comment by koral--** [comment] 2022-12-26 12:09
> Please attach a project which reproduces this issue 

This is still missing.

**Comment by RishabhSRS** [comment] 2022-12-28 11:20
hey, due to our company policies I am unable to attach project name but I can provide you with gif that we are using as this crash was reported in crashlytics on real-user end, could you please help me out ?

**Comment by koral--** [comment] 2022-12-28 11:25
I mean the reproducer project - a code sample which reproduces the issue.
The affected GIF file should be a part of it.
Only GIF may or may not be sufficient for me to investigate the cause.

**Comment by koral--** [comment] 2023-01-13 14:56
Closing due to the lack of reproduce steps.

**Closed as completed by koral--** 2023-01-13 14:56 UTC
Labels: needs info
