### ISSUE TITLE
gif can not show on android 5.1

### ISSUE THREAD

**Issue by zhaoli-android** [koral--/android-gif-drawable#247] opened 2016-01-19 04:50 UTC
hi,i use this succeed on android 4.0,but it have some problem on 5.1,the gif can not show ,and there is no error log,do you know the reason?

**Comment by koral--** [comment] 2016-01-19 12:22
Does the problem persist if you call `view.setLayerType(View.LAYER_TYPE_SOFTWARE, null)`? where `view` is a `View` displaying GIF.

**Comment by divyanshgoenka-tinklabs** [comment] 2016-01-22 03:48
Hi, I 'm facing the same problem. Yes, the problem persists even after adding view.setLayerType(View.LAYER_TYPE_SOFTWARE, null)

**Comment by koral--** [comment] 2016-01-22 04:05
Could you provide a snippet which reproduces this issue?

**Comment by divyanshgoenka-tinklabs** [comment] 2016-01-22 04:06
```
gifImageView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
gifImageView.setImageDrawable(gifDrawable);
gifDrawable.start();
```

**Comment by koral--** [comment] 2016-01-22 13:53
What is a device model?

**Comment by koral--** [comment] 2016-01-25 00:17
I could not reproduce this issue and have no idea about the reason. It may be something device-specific. Theoretically nothing may be drawn when bitmap dimensions exceed maximums supported by `Canvas` - [Canvas#getMaximumBitmapHeight()](https://developer.android.com/reference/android/graphics/Canvas.html#getMaximumBitmapHeight()). But those values on devices running Android 5.1 are probably huge and probably that is not a reason.

I'll leave this issue open until some more info is provided which helps localize the reason.

**Comment by koral--** [comment] 2016-03-26 23:33
It maybe the same case as described in #260. This issue is older, however there is more info in #260 so I'm marking this as duplicate. See especially: https://github.com/koral--/android-gif-drawable/issues/260#issuecomment-201949696

**Closed by koral--** 2016-03-26 23:33 UTC
Labels: duplicate
