### ISSUE TITLE
can gif reverse play ?

### ISSUE THREAD

**Issue by luojin** [koral--/android-gif-drawable#381] opened 2017-01-17 08:56 UTC
as title describe, can a gifview display gif image with reverse order?

**Comment by koral--** [comment] 2017-01-17 23:28
No, currently it is not possible, but may be added in the future. See https://github.com/koral--/android-gif-drawable/issues/274#issuecomment-210098076 for more info.
Closing this issue as a duplicate of #274

**Closed by koral--** 2017-01-17 23:28 UTC
Labels: question
