### ISSUE TITLE
Fatal Exception: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by alexandre-thauvin** [koral--/android-gif-drawable#735] opened 2020-04-25 21:37 UTC
Hello ! Thanks for this nice lib !
I have this error on a Nexus 5X Android 8.0.0
I'm using Bundle App (.aab) to deploy on play store. Is it related to this [issue](https://github.com/koral--/android-gif-drawable/issues/666)
impl:
`implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.17'
`

```
Caused by com.getkeepsafe.relinker.MissingLibraryException
libpl_droidsonroids_gif.so
com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary (ApkLibraryInstaller.java:128)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:180)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:136)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:70)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:51)
pl.droidsonroids.gif.LibraryLoader.loadLibrary (LibraryLoader.java:52)
pl.droidsonroids.gif.GifInfoHandle.<clinit> (GifInfoHandle.java:27)
pl.droidsonroids.gif.GifDrawable.<init> (GifDrawable.java:159)
pl.droidsonroids.gif.GifDrawable.<init> (GifDrawable.java:94)
pl.droidsonroids.gif.GifViewUtils.setResource (GifViewUtils.java:55)
pl.droidsonroids.gif.GifImageView.setImageResource (GifImageView.java:101)
com.weedmanager.myweedmanager.SplashActivity.onCreate (SplashActivity.kt:52)
```

```
Caused by com.getkeepsafe.relinker.MissingLibraryException
com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary (ApkLibraryInstaller.java:128)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:180)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:136)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:70)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:51)
pl.droidsonroids.gif.LibraryLoader.loadLibrary (LibraryLoader.java:52)
pl.droidsonroids.gif.GifInfoHandle.<clinit> (GifInfoHandle.java:27)
pl.droidsonroids.gif.GifDrawable.<init> (GifDrawable.java:159)
pl.droidsonroids.gif.GifDrawable.<init> (GifDrawable.java:94)
pl.droidsonroids.gif.GifViewUtils.setResource (GifViewUtils.java:55)
pl.droidsonroids.gif.GifImageView.setImageResource (GifImageView.java:101)
com.weedmanager.myweedmanager.SplashActivity.onCreate (SplashActivity.kt:52)
android.app.Activity.performCreate (Activity.java:6975)
```

**EDIT:**
There is the simple implementation:
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_splash)
        //stuff
        ivLogo.setImageResource(R.drawable.bandera_gif)
}
```
ivLogo:
```xml
<pl.droidsonroids.gif.GifImageView
            android:paddingEnd="100dp"
            android:paddingStart="100dp"
            android:id="@+id/ivLogo"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />
```
The GifImageView is the only view I have in my whole layout.

How I build my AABs:
Build -> Generate Signed APK/AAB -> AAB -> Next (choosing keystone screen) -> release -> Finish

If you need any more information do not hesitate to tell me!

**Comment by koral--** [comment] 2020-04-26 01:18
Could you share a minimal project which reproduces this issue along with the info how are you building AABs?

**Comment by alexandre-thauvin** [comment] 2020-04-26 09:59
Hi koral !
Thanks for your time !
I just edited my original message :)

**Comment by guness** [comment] 2020-05-27 10:59
Hello @koral-- , @alexandre-thauvin ;

I am facing similar error on another library. could you check if this is related:  https://github.com/KeepSafe/ReLinker/issues/47

**Comment by koral--** [comment] 2020-07-03 17:21
Thanks @guness for the info. Sorry @alexandre-thauvin for my slowness.
Message in linked exception is a little bit different. But ReLinker has been updated in the meantime I'll integrate those changes.

**Comment by Riaxter** [comment] 2020-11-29 15:56
Hi @koral--. I think I'm having same issue here 😢 
Could you let me know when it will be fixed?

**Comment by koral--** [comment] 2020-11-29 22:57
@Riaxter which library version are you using?

**Comment by Riaxter** [comment] 2020-12-03 01:20
@koral-- oh, sorry for late reply, I'm using 1.2.19 version
```
implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.19'
```

**Comment by Riaxter** [comment] 2020-12-04 16:20
@koral-- There is new update for this issue:
1. No crash occurred with aab file on Google Play store.
2. But still crashing with building in local with: Android studio -> Run tab -> Edit configurations... -> Deploy -> Change to `APK from app bundle`

**Comment by koral--** [comment] 2020-12-04 16:24
Good catch @Riaxter !
Will try to investigate using that scenario.

**Comment by ZhangHui1024** [comment] 2022-07-26 09:19
is resolved now? I have the same issue here now.

**Comment by koral--** [comment] 2022-07-26 09:40
Sorry for the lack of answer, but I could not reproduce an issue where the same app on the same device is working when installed from play store but not locally from apk.

Regarding the MissingLibrary exception itself, look also here: https://github.com/koral--/android-gif-drawable/issues/778#issuecomment-1179306620

**Closed as completed** 2022-08-10 22:27 UTC
