### ISSUE TITLE
tearing problem

### ISSUE THREAD

**Issue by adrich** [koral--/android-gif-drawable#267] opened 2016-04-07 06:09 UTC
I use the gif-drawable to display gifs in a live-wallpaper.
So the gif-drawable draws on a SurfaceHolder canvas.

Sometimes the frame is not properly drawn. The drawn image partially consits of 2 different frames.
As a test, I've made a gif which switches between a green and blue frame. 
Take a look at the screenshot as an example for the problem.

![gif tearing](https://cloud.githubusercontent.com/assets/10379390/14341947/528e717e-fc96-11e5-828d-cf8f7cdac403.jpg)

**Code snipped:**

```
    private Runnable drawGIF = new Runnable() {
        public void run() {
            draw();
        }
    };

    private void draw() {
                Canvas canvas = holder.lockCanvas();
                canvas.drawColor(Color.BLACK);

                canvas.save();
                // canvas scale translate
                gifDrawable.draw(canvas);
                canvas.restore();

                handler.removeCallbacks(drawGIF);
                handler.postDelayed(drawGIF, 30);
    }
```

This is the test image:

![blue-green](https://cloud.githubusercontent.com/assets/10379390/14342125/c3412e38-fc97-11e5-9627-a202f84b8070.gif)

**Comment by koral--** [comment] 2016-04-07 15:43
This is because drawing is not synchronized with rendering. Currently it is default behavior by design for performance reasons. You can override that by instructing your `GifDrawable` to use your custom executor.
One of the solutions in your case may be something like that:

Drawable creation:
```java
		ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(1);
		ExecutorHandler handler = new ExecutorHandler(executor);
		gifDrawable = new GifDrawableBuilder().taskExecutor(executor).from(source).build();
```
custom handler:
```java
	static class ExecutorHandler extends Handler{
		private final ScheduledThreadPoolExecutor mExecutor;

		public ExecutorHandler(ScheduledThreadPoolExecutor executor){
			mExecutor=executor;
		}
		@Override
		public void dispatchMessage(final Message msg) {
			mExecutor.submit(new Runnable(){
				@Override
				public void run() {
					ExecutorHandler.super.dispatchMessage(msg);
				}
			});
		}
	}
```
or you can use executor inside `draw()` directly without handler.

I'll add example for case like yours to sample project. So I'm leaving this issue open until it is ready.

**Comment by oberflansch** [comment] 2016-04-08 10:01
Thank a lot. 
I didn't notice the possibility to set a custom executor. 
Now everything is working fine. 
Great lib btw.

**Comment by koral--** [comment] 2018-04-30 19:10
Adding live wallpaper sample is tracked in https://github.com/koral--/android-gif-drawable/issues/298 so I'm closing this issue.

**Closed by koral--** 2018-04-30 19:10 UTC
Labels: needs sample

**Comment by koral--** [comment] 2018-05-07 22:40
I'll try to add wallpaper to sample project.

**Comment by AndroidDeveloperLB** [comment] 2018-05-07 22:43
Wow thank you!
