### ISSUE TITLE
The abnormal invalidationDelay in RenderTask causes the animation to stop playing

### ISSUE THREAD

**Issue by panpf** [koral--/android-gif-drawable#829] opened 2023-07-28 07:27 UTC
Symptom:
1. Play animation for a while and then stop playing
2. The playing time is not fixed, sometimes short and sometimes long
3. There is no problem with the real device (only API 27 has been tested), and there is a problem with the Android emulator (API 24, 25, 26, 27, 28 have been tested with exceptions)

Debug found:
1. By printing the log in debug mode, it is found that the abnormal invalidationDelay in RenderTask will cause the frame interval to be very long
2. The normal invalidationDelay is around 90, and the abnormal invalidationDelay is around 450000

Test environment:
1. Android emulator version v33.3.13
2. Android version API 24, 25, 26, 27, 28 are abnormal
3. android-gif-drawable version 1.2.15 and 1.2.27 
4. Mac book pro 2021  M1pro

Looking forward to your reply, thank you!

**Comment by koral--** [comment] 2023-07-28 11:57
Could you share a project/snippet reproducing this issue?

**Comment by panpf** [comment] 2023-07-28 13:08
val imageView =...
val gifDrawable = GifDrawable(context.assets, "dog.jpg")
imageView.setImageDrawable(gifDrawable)
gifDrawable.start()

**Comment by koral--** [comment] 2023-07-28 14:04
> Play animation for a while and then stop playing

There is no play and stop in your snippet.

**Comment by panpf** [comment] 2023-07-28 14:12
Sorry, less copy a line, already added in the previous one

**Comment by koral--** [comment] 2023-07-30 13:08
OK, there is a play but no stop. Also there is no printing anything to the log and no GIF file.
Please post a complete example.

**Comment by panpf** [comment] 2023-07-30 15:07
This is the test project:
[GifTest.zip](https://github.com/koral--/android-gif-drawable/files/12209526/GifTest.zip)

The screenshot below is the debug log:

<img width="1193" alt="Snipaste_2023-07-30_23-01-43" src="https://github.com/koral--/android-gif-drawable/assets/3250512/c2d98a66-29aa-4ee0-bb0d-96ff35f1f51f">

<img width="1836" alt="Snipaste_2023-07-30_23-03-24" src="https://github.com/koral--/android-gif-drawable/assets/3250512/a30c4c74-15fc-4012-804d-0f145f5fe1f3">

**Comment by panpf** [comment] 2023-07-31 01:43
It should be noted that this is not a problem with a certain gif, because the gif I got from the GIPHY API has the same problem

**Comment by panpf** [comment] 2023-08-02 06:54
Has the problem been reproduced?

**Comment by koral--** [comment] 2023-08-02 11:27
No, I couldn't reproduce that. Tried on various emulators.
I'll close this issue for now, but if there will be some new information I'll take a look.

**Closed as completed by koral--** 2023-08-02 11:27 UTC
Labels: can't reproduce
