### ISSUE TITLE
Not Animating when using  gifImageView.setImageBitmap(aBigBitmap);

### ISSUE THREAD

**Issue by kundansdere** [koral--/android-gif-drawable#353] opened 2016-10-17 16:26 UTC
View is not animating with set bitmap
 gifImageView.setImageBitmap(aBigBitmap);
 gifImageView.animate();

I am trying to set gif image from url. Using Aysnc task to get Url converted in bitmap. Image getting loaded But not animating

**Comment by koral--** [comment] 2016-10-17 16:32
`Bitmap` is a static image it contains only one frame and cannot be animated. You need to create `GifDrawable` and then use `gifImageView.setImageDrawable()`.

**Comment by kundansdere** [comment] 2016-10-18 05:05
I tried in this way 
```
 URL ulrn = new URL(url);
            HttpURLConnection con = (HttpURLConnection) ulrn.openConnection();
            InputStream is = con.getInputStream();
            BufferedInputStream bis = new BufferedInputStream(is);
            bmp = new GifDrawable(bis);
```
and I ma getting `pl.droidsonroids.gif.GifIOException: GifError 1000: No frames found, at least one frame required`

**Comment by koral--** [comment] 2016-10-18 11:31
Could you paste a URL here?

**Comment by kundansdere** [comment] 2016-10-18 11:46
http://dyotasolutions.com/notificationimages/3.gif

**Comment by koral--** [comment] 2016-10-18 13:10
OK, I'll check that.

**Comment by GeniusAtamans** [comment] 2016-10-18 22:13
Have same problem.

**Comment by koral--** [comment] 2016-10-18 23:58
OK, I can reproduce this issue. I need to investigate it further.
For now, workaround is to buffer GIF data, eg. like that:
```
					URL ulrn = new URL("http://dyotasolutions.com/notificationimages/3.gif");
					HttpURLConnection con = (HttpURLConnection) ulrn.openConnection();
					InputStream is = con.getInputStream();
					BufferedInputStream bis = new BufferedInputStream(is);
					final File file = new File(getCacheDir(), "tmp.gif");
					FileOutputStream fileOutputStream = new FileOutputStream(file);
					byte[] buffer = new byte[1024];
					int len;
					while ((len = bis.read(buffer)) > 0) {
						fileOutputStream.write(buffer, 0, len);
					}
					fileOutputStream.flush();
					fileOutputStream.close();
					new GifDrawable(file);
```

**Comment by GeniusAtamans** [comment] 2016-10-19 15:23
Fatal signal 11 (SIGSEGV)
I getting this almost all time

**Comment by koral--** [comment] 2016-10-19 15:27
@GeniusAtamans please attach complete logcat output, in new issue because it seems to be different.

**Comment by koral--** [comment] 2016-10-22 23:28
OK, there was a bug in `InputStream` reading function which may lead to random error or segmentation faults when underlying `InputStream#available()` returned 0. 
It is fixed now, so code like that https://github.com/koral--/android-gif-drawable/issues/353#issuecomment-254407640 should work assuming that buffer size is large enough.

The last part is important. Especially for @kundansdere because attached GIF (708 KB) is larger than default buffer size (8 KB).
Minimum buffer size is equal to entire GIF size excluding header. It may be just GIF size for simplicity.

So in case of attached GIF, stream should be created like that:
`BufferedInputStream bis = new BufferedInputStream(is, <upper bound of GIF size>);` or custom implementation of `BufferedInputStream` with growing buffer may be used.

Requirement is that stream must be able to reset from the end to position just before first frame.

**Closed by koral--** 2016-10-22 23:28 UTC
Labels: bug
