### ISSUE TITLE
v1.0.12 fails to render on HTC One (M7)

### ISSUE THREAD

**Issue by Wavesonics** [koral--/android-gif-drawable#95] opened 2014-11-14 22:37 UTC
I haven't had time to really dig into this yet, and I'm leaving for a week in a couple of hours, but I thought I should get this tracked to see if anyone else was seeing this.

Release 1.0.12 seems to do everything correctly, I've stepped through and it's loading and decoding all seems correct, no errors in the logs either, but it simply does not draw anything.

This only repros for me so far on the HTC One (M7) running Android 4.1.2

I've tested it on the Nexus 4, 5, 9, Samsung Galaxy 3, 4, 5, 10 and it appears to be fine on those.

For now I'm rolling back to 1.0.11 where the bug does not repro.

**Comment by Doctoror** [comment] 2015-04-10 16:43
@Wavesonics I had a problem that Drawable decoded from AssetInputStream drew blank data until I wrapped it with BufferedInputStream. Also I had libc SIGSEV crash on some devices when tried to decode AssetInputStream now wrapped with BufferedInputStream.

@koral You should probably accept only BufferedInputStream as a parameter and throw IllegalArgumentException if the InputStream is not a BufferedInputStream (not only if mark is not supported as currently).

**Comment by koral--** [comment] 2015-04-10 20:51
@Doctoror could you provide stacktrace for that SIGSEGV? Why do you think `AssetInputStream` needs to be wrapped with `BufferedInputStream`? 

I see that in your project you are using inappropriate mode: https://github.com/Doctoror/ImageFactory/blob/be35339df622eb92c772184ff27f691cb0788efe/library/src/androidTest/java/com/doctoror/imagefactory/test/ImageFactoryTest.java#L38. According to the documentation [ACCESS_RANDOM](http://developer.android.com/reference/android/content/res/AssetManager.html#ACCESS_RANDOM) should be used because seeking backward is needed.

I've played with `AssetInputStream` (with correct mode set) and could not reproduce any blank data nor SIGSEGV.

However I've found a bug: if `InputStream#mark()` throws an exception and further read fails so `GifIOException` is trying to be thrown, SIGABRT is raised - first exception is pending so we cannot throw another one (without clearing that first). This is fixed in be6f8a7018e491ced92106b9902f8bb62d56312b.

Eg. `AssetInputStream.mark#mark()` throws an NPE if stream has been closed:
```java
    java.lang.NullPointerException: asset
            at android.content.res.AssetManager.seekAsset(Native Method)
            at android.content.res.AssetManager.access$600(AssetManager.java:36)
            at android.content.res.AssetManager$AssetInputStream.mark(AssetManager.java:574)
            at pl.droidsonroids.gif.GifInfoHandle.openStream(Native Method)
            at pl.droidsonroids.gif.GifInfoHandle.openMarkableInputStream(GifInfoHandle.java:96)
            at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:133)
```

So (with the current level of knowledge) that what you said can be related to Wavesonic's post only if he is using `AssetInputStream` with incorrect mode or he is ignoring exceptions, but he hasn't written which source he is using.

**Comment by Doctoror** [comment] 2015-04-11 10:20
@koral I will get my hands on the device which crashed on Monday and post an update whether I could reproduce SIGSEGV again.

When I've had blank images I didn't get any exceptions caught, it went through like everything was fine.
I will try to reproduce that later today and post an update here as well.

And thanks for ACCESS_RANDOM tip.

**Comment by Wavesonics** [comment] 2015-04-13 17:53
I've retested using releases 1.1.3 and 1.1.5 and can no longer reproduce the specific error I was seeing.

I recommend closing this issue and opening a new one for the other errors users are reporting here.

**Comment by koral--** [comment] 2015-04-13 19:44
OK, @Doctoror please fill new issue if you encounter SIGSEGV.

**Closed by koral--** 2015-04-13 19:44 UTC
Labels: can't reproduce
