### ISSUE TITLE
black screen phenomenon

### ISSUE THREAD

**Issue by mshandan** [koral--/android-gif-drawable#822] opened 2023-05-22 09:54 UTC
Hello, I have encountered some issues while using it. Mainly using the seekToFrame() method, there will be a black screen phenomenon.

**Comment by koral--** [comment] 2023-05-22 10:21
Please attach the reproducer project.

**Comment by mshandan** [comment] 2023-05-22 10:51
class TrainingMusicFragment : LazyBaseFragment() {

    private lateinit var gifImageView: GifImageView
    private lateinit var gifDrawable: GifDrawable

    private val frameCount:Int = 58

    private lateinit var llWave : LinearLayout
    private var realTimeView1: RealTimeView? = null
    private var realTimeView2: RealTimeView? = null
    private var realTimeView3: RealTimeView? = null
    private var maiboWaveView: LineChart? = null

    private var isShow = false
    private var isEyeMove = false
    private var cp = 0
    private var tp = 0
    private var delay = 300L
    private lateinit var mHandle: Handler

    private var mMusicDisplayType = Constants.MusicDisplayType.DRAWABLE

    private var mSsvSubtitle: SimpleSubtitleView? = null

    companion object {
        fun newInstance(materialUrl: String, isEyeMove: Boolean,gif: Int = 0): TrainingMusicFragment {
            val args = Bundle()
            args.putString("URL", materialUrl)
            args.putInt("Gif", gif)
            args.putBoolean("isEyeMove", isEyeMove)
            val fragment = TrainingMusicFragment()
            fragment.arguments = args
            return fragment
        }

        const val WAVE_TYPE_1 = "0x2001" //心率,呼吸,放松指数(需呼吸带)
        const val WAVE_TYPE_2 = "0x2002" //心率,呼吸(需呼吸带),脉搏波(需指夹)
        const val WAVE_TYPE_3 = "0x2003" //心率,呼吸(需呼吸带),皮电(需指夹)
        const val WAVE_TYPE_4 = "0x2004" //皮电,脉搏波(需指夹)
        const val WAVE_TYPE_5 = "0x2005" //脉搏波(需指夹)
    }

    override fun getLayoutId() = R.layout.fragment_training_music

    override fun initView(rootView: View) {
        mMusicDisplayType = SPUtil.getSharedValue(SPUtil.Keys.MUSIC_DISPLAY_TYPE, Constants.MusicDisplayType.DEFAULT)
        initHandle()
        llWave = rootView.ll_wave
        gifImageView = rootView.gifImageView
        if(arguments!!.getInt("Gif")!=0){
            gifImageView.setImageResource(arguments!!.getInt("Gif"))
        }
        maiboWaveView = rootView.include_maibo.maiboWaveView
        mSsvSubtitle = rootView.ssv_subtitle
        gifDrawable = gifImageView.drawable as GifDrawable
        gifDrawable.stop()
    }

    private fun initWave() {
        if (mMusicDisplayType == Constants.MusicDisplayType.DRAWABLE) {
            llWave.visibility = View.GONE
        } else {
            gifImageView.visibility = View.GONE

            when (mMusicDisplayType) {
                WAVE_TYPE_1, WAVE_TYPE_3 -> {
                    llWave.include_maibo.visibility = View.GONE
                    initRealTimeView1()
                    initRealTimeView2()
                    initRealTimeView3()
                }

                WAVE_TYPE_2 -> {
                    llWave.include_3.visibility = View.GONE
                    initRealTimeView1()
                    initRealTimeView2()
                    initialppgchart()
                }

                WAVE_TYPE_4 -> {
                    llWave.include_2.visibility = View.GONE
                    llWave.include_3.visibility = View.GONE
                    initRealTimeView1()
                    initialppgchart()
                }
                WAVE_TYPE_5 -> {
                    llWave.include_1.visibility = View.GONE
                    llWave.include_2.visibility = View.GONE
                    llWave.include_3.visibility = View.GONE
                    initialppgchart()
                }
            }
        }

    }

    private fun initRealTimeView1() {
        if (realTimeView1 == null) {
            realTimeView1 = RealTimeView(activity)
            realTimeView1!!.setGraphLineColor(activity!!.resources.getColor(R.color.white))
            realTimeView1!!.setBondValue(-1f,1f)
            llWave.include_1.ll_content.addView(realTimeView1)
        }
    }

    private fun initRealTimeView2() {
        if (realTimeView2 == null) {
            realTimeView2 = RealTimeView(activity)
            realTimeView2!!.setGraphLineColor(activity!!.resources.getColor(R.color.white))
            realTimeView2!!.setBondValue(-1f,1f)
            llWave.include_2.ll_content.addView(realTimeView2)
        }
    }

    private fun initRealTimeView3() {
        if (realTimeView3 == null) {
            realTimeView3 = RealTimeView(activity)
            realTimeView3!!.setGraphLineColor(activity!!.resources.getColor(R.color.white))
            realTimeView3!!.setBondValue(-1f,1f)
            llWave.include_3.ll_content.addView(realTimeView3)
        }
    }

    private fun removeViews() {
        llWave.include_1.ll_content.removeAllViews()
        realTimeView1 = null
        llWave.include_2.ll_content.removeAllViews()
        realTimeView2 = null
        llWave.include_3.ll_content.removeAllViews()
        realTimeView3 = null
        maiboWaveView?.clearAllViewportJobs()
        maiboWaveView?.removeAllViews()
        maiboWaveView = null
    }

    override fun onFragmentLoad() {
        MusicManager.getInstance().addMusicStateInterface(musicStateInterface)
        val musicUrl = arguments!!.getString("URL")
        Log.e(TAG, "当前播放：${musicUrl}")
        isEyeMove = arguments!!.getBoolean("isEyeMove")
        musicUrl?.takeIf { it.isNotEmpty() }?.apply { MusicManager.getInstance().firstStart(UriUtils.encodeUrl(this)) }
        initWave()
        realTimeView1?.doStart()
        realTimeView2?.doStart()
        realTimeView3?.doStart()
        isShow = true
    }

    override fun onFragmentLoadStop() {
        isShow = false
        mHandle.removeCallbacksAndMessages(null)
        realTimeView1?.doStop()
        realTimeView2?.doStop()
        realTimeView3?.doStop()
        removeViews()
        MusicManager.getInstance().releaseMusicStateInterface()
        try {
            MusicManager.getInstance().stop()
        } catch (e: Exception) {
            Log.e(TAG, "MusicManager.getInstance().stop()异常")
        }
    }

    private fun initHandle() {
        mHandle = Handler(object : Handler.Callback {
            override fun handleMessage(msg: Message?): Boolean {
                msg?.apply {
                    when (what) {
                        0x100 -> {
                            when {
                                cp < tp -> {
                                    cp++
                                    gifDrawable.seekToFrame(cp)
                                    gifDrawable.stop()
                                    mHandle.sendEmptyMessageDelayed(0x100, delay)
                                }
                                cp == tp -> {

                                }
                                else -> {
                                    cp--
                                    gifDrawable.seekToFrame(cp)
                                    gifDrawable.stop()
                                    mHandle.sendEmptyMessageDelayed(0x100, delay)
                                }
                            }
                        }
                        0x101 ->{
                            if (listPPGData1.size >= 100) {//用于波形图表的显示，滤波后的红外信号
                                leftAxis?.axisMaximum = lo.max_List_Val_f(lo.subList_float(listPPGData1, 500)) + 0.005f
                                leftAxis?.axisMinimum = lo.min_List_Val_f(lo.subList_float(listPPGData1, 500)) - 0.002f
                            }
                            mHandle.sendEmptyMessageDelayed(0x101,3000)
                        }
                    }
                }
                return false
            }
        })
    }

    override fun onDestroy() {
        super.onDestroy()
        mHandle.removeCallbacksAndMessages(null)
        mSsvSubtitle?.destroy()
//        MusicManager.getInstance().release()
        gifDrawable.recycle()
    }

    private val musicStateInterface = object : MusicStateInterface {
        override fun onPreparing() {

        }

        override fun onPrepared(mp: MediaPlayer) {
            mSsvSubtitle?.bindToMediaPlayer(mp)
            mSsvSubtitle?.setSubtitlePath("")
        }

        override fun onstart() {

        }

        override fun onPause() {

        }

        override fun onStop() {

        }

        override fun onCompletion(mp: MediaPlayer) {
            if (isEyeMove) {
                val loadingDialog = LoadingDialog(context!!)
                loadingDialog.setIsCanceledOnTouchOutside(false)
                loadingDialog.show("接下来请完成量表测评")
                llWave.postDelayed({
                    if (llWave != null) {
                        loadingDialog.dismiss()
                        TestPaperInfoActivity.APIs.actionStart(context!!, "8b571112-90a1-49b5-b048-6ce828ae0572", "0", true)
                    }
                }, 2000)
            } else {
                (activity as NewTrainingActivity).nextFragment()
            }
        }

        override fun onError(mp: MediaPlayer, what: Int, extra: Int) {

        }
    }

    //荷花入口
    private var mLastTp = -1
    fun seekGif(tagetFrameIndex: Int, delayTime: Long = 300, isEnlarge: Boolean = false) {
        if (isShow) {
            if (isEnlarge) {
                if (tagetFrameIndex == mLastTp) {//防止回溯到原来的帧数。相等说明已经在当前的帧数，荷花不用动.
                    return
                }
                val enlargeData =
                        if (mLastTp != -1) {
                            (tagetFrameIndex - mLastTp) * 2 + tagetFrameIndex
                        } else {
                            tagetFrameIndex
                        }
                tp = when {
                    enlargeData < 0 -> 0
                    enlargeData > frameCount -> frameCount
                    else -> enlargeData
                }
                mLastTp = tagetFrameIndex
                Log.e("kunggka555", "tagetFrameIndex=$tagetFrameIndex; enlargeData=$enlargeData; tp=$tp")
            } else {
                tp = when {
                    tagetFrameIndex < 0 -> 0
                    tagetFrameIndex > frameCount -> frameCount
                    else -> tagetFrameIndex
                }
                Log.e("kunggka555", "@@@tagetFrameIndex=$tagetFrameIndex; tp=$tp")
            }
            delay = delayTime
            mHandle.removeCallbacksAndMessages(null)
            mHandle.sendEmptyMessageDelayed(0x100, delay)
        }
    }

    //心率,呼吸,放松指数
    //心率,呼吸,脉搏波
    //心率,呼吸,皮电
    //皮电,脉搏波

    //波形图入口
    private var dataXY = WavePictureBean.DataXY(0f,0f)
    @Synchronized
    fun setWaveData(dataList: MutableList<WavePictureBean>,index: Int) {
        if (isShow) {
//            Log.e("kunggka3", "setWaveData 心率size=${dataList[0].data.size} 呼吸size=${dataList[1].data.size} 脉搏波size=${dataList[2].data.size} start")
            when (mMusicDisplayType) {
                WAVE_TYPE_1 -> {//心率，呼吸 放松指数
                    dataList[0].data.takeIf { it.isNotEmpty() }?.also { stack ->
                        llWave.include_1.tv_name.text = dataList[0].name
                        dataXY =stack.pop()
                        realTimeView1?.add(PointF(dataXY.x,dataXY.y),true)
                    }
                    dataList[1].data.takeIf { it.isNotEmpty() }?.also { stack ->
                        llWave.include_2.tv_name.text = dataList[1].name
                        dataXY = stack.pop()
                        realTimeView2?.add(PointF(dataXY.x,dataXY.y),true)
                    }
                    dataList[2].data.takeIf { it.isNotEmpty() }?.also {stack ->
                        llWave.include_3.tv_name.text = dataList[2].name
                        dataXY = stack.pop()
                        realTimeView3?.add(PointF(dataXY.x,dataXY.y),false)
                    }
                }

                WAVE_TYPE_2 -> {
                    dataList[0].data.takeIf { it.isNotEmpty() }?.also { stack ->
                        llWave.include_1.tv_name.text = dataList[0].name
                        dataXY = stack.pop()
                        realTimeView1?.add(PointF(dataXY.x,dataXY.y),true)
                    }
                    dataList[1].data.takeIf { it.isNotEmpty() }?.also { stack ->
                        llWave.include_2.tv_name.text = dataList[1].name
                        dataXY = stack.pop()
                        realTimeView2?.add(PointF(dataXY.x,dataXY.y),true)
                    }
                    dataList[2].data.takeIf { it.isNotEmpty() }?.also { stack ->
                        llWave.include_maibo.tv_maiboName.text = dataList[2].name
                        dataXY = stack.pop()
                        listPPGData1.add(dataXY.y)
                        addppgEntry(dataXY.y)
                    }
                }

                WAVE_TYPE_3 -> {
                    dataList[0].data.takeIf { it.isNotEmpty() }?.also { stack ->
                        llWave.include_1.tv_name.text = dataList[0].name
                        dataXY = stack.pop()
                        realTimeView1?.add(PointF(dataXY.x,dataXY.y),true)
                    }
                    dataList[1].data.takeIf { it.isNotEmpty() }?.also { stack ->
                        llWave.include_2.tv_name.text = dataList[1].name
                        dataXY = stack.pop()
                        realTimeView2?.add(PointF(dataXY.x,dataXY.y),true)
                    }
                    dataList[2].data.takeIf { it.isNotEmpty() }?.also { stack ->
                        llWave.include_3.tv_name.text = dataList[2].name
                        dataXY = stack.pop()
                        realTimeView3?.add(PointF(dataXY.x,dataXY.y),true)
                    }
                }

                WAVE_TYPE_4 -> {
                    dataList[0].data.takeIf { it.isNotEmpty() }?.also { stack ->
                        llWave.include_1.tv_name.text = dataList[0].name
                        dataXY = stack.pop()
                        realTimeView1?.add(PointF(dataXY.x,dataXY.y),true)
                    }
                    dataList[1].data.takeIf { it.isNotEmpty() }?.also { stack ->
                        llWave.include_maibo.tv_maiboName.text = dataList[1].name
                        dataXY =stack.pop()
                        listPPGData1.add(dataXY.y)
                        addppgEntry(dataXY.y)
                    }
                }

                WAVE_TYPE_5 -> {
                    dataList[0].data.takeIf { it.isNotEmpty() }?.also { stack ->
                        llWave.include_maibo.tv_maiboName.text = dataList[0].name
                        dataXY =stack.pop()
                        listPPGData1.add(dataXY.y)
                        addppgEntry(dataXY.y)
                    }
                }
            }
        }
    }

    internal var leftAxis: YAxis? = null
    internal val listPPGData1 = Collections.synchronizedList(LinkedList<Float>())
    internal var lo = ListOperation()
    private fun initialppgchart() {
        if (maiboWaveView == null) {
            return
        }
//        maiboWaveView!!.setOnChartValueSelectedListener(object : OnChartValueSelectedListener{
//            override fun onNothingSelected() {
//            }
//            override fun onValueSelected(e: Entry?, h: Highlight?) {
//            }
//        })
        maiboWaveView?.let {
            it.description.isEnabled = false// 禁止描述性语言
            it.setTouchEnabled(false)// 不能触摸
            it.isDragEnabled = false// enable scaling and dragging
            it.setScaleEnabled(false)
            it.setDrawGridBackground(false)
            it.setPinchZoom(true)// if disabled, scaling can be done on x- and y-axis separately
            it.setBackgroundColor(Color.BLACK)// set an alternative background color
            val data = LineData()
            data.setValueTextColor(Color.WHITE)
            it.data = data
        }

        val l = maiboWaveView!!.legend
        // modify the legend ...
        l.form = Legend.LegendForm.LINE
        l.textColor = Color.WHITE
        val xl = maiboWaveView!!.xAxis
        xl.textColor = Color.WHITE
        xl.setDrawGridLines(false)
        xl.setAvoidFirstLastClipping(true)
        xl.isEnabled = false
        leftAxis = maiboWaveView!!.axisLeft
        leftAxis?.isEnabled = false
        leftAxis?.textColor = Color.WHITE
        leftAxis?.setDrawGridLines(true)
        val rightAxis = maiboWaveView!!.axisRight
        rightAxis.isEnabled = false
        mHandle.sendEmptyMessage(0x101)
    }

    private fun addppgEntry(ppg: Float) {
        if (!isShow && maiboWaveView?.isAttachedToWindow == true) {
            return
        }
        val data = maiboWaveView?.data
        if (data != null) {
            var set: ILineDataSet? = data.getDataSetByIndex(0)
            // set.addEntry(...); // can be called as well
            if (set == null) {
                set = createppgSet()
                data.addDataSet(set)
            }
            data.addEntry(Entry(set.entryCount.toFloat(), ppg), 0)
            data.notifyDataChanged()
            maiboWaveView?.notifyDataSetChanged()// let the chart know it's data has changed
            maiboWaveView?.setVisibleXRangeMaximum(500f)// 设置一屏显示的最大采样点数
            if (isShow && maiboWaveView?.isAttachedToWindow == true) {
                maiboWaveView?.moveViewToX(data.entryCount.toFloat())// move to the latest entry
            }
        }
    }

    private fun createppgSet(): LineDataSet {
        val set = LineDataSet(null, "")
        set.axisDependency = YAxis.AxisDependency.LEFT
        set.color = Color.GREEN
        set.lineWidth = 1f
        set.setDrawCircles(false)
        set.setDrawFilled(true)
        set.fillColor = Color.GRAY
        set.fillAlpha = 100
        set.highLightColor = Color.WHITE
        set.valueTextColor = Color.WHITE
        set.valueTextSize = 9f
        set.setDrawValues(false)
        return set
    }
}

**Comment by mshandan** [comment] 2023-05-22 10:53
<pl.droidsonroids.gif.GifImageView
        android:id="@+id/gifImageView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="fitXY"
        android:src="@mipmap/lotus" />

**Comment by koral--** [comment] 2023-05-22 11:19
Could you create a repository for that?
Don't forget to include the affected GIF file.

**Comment by mshandan** [comment] 2023-05-23 02:27
hello，I wrote a simple repository that can basically reproduce the phenomenon of lag, which is a white screen phenomenon.

https://github.com/mshandan/demo

**Comment by mshandan** [comment] 2023-05-23 02:28
I look forward to your reply very much. I'm not sure if my writing is incorrect. This phenomenon has indeed caused me a lot of trouble.

**Comment by koral--** [comment] 2023-05-23 11:04
OK thanks, I'll check that.

**Comment by koral--** [comment] 2023-05-23 12:46
It seems to be the same issue as https://github.com/koral--/android-gif-drawable/issues/267#issuecomment-206962158
You can modify your Handler like in the linked comment.

**Comment by mshandan** [comment] 2023-05-23 13:05
Okay, I'll take a look

**Comment by mshandan** [comment] 2023-05-23 13:36
I'm very sorry, I can't understand what this "source" means? I don't know how to associate GifImageView in XML with this. Can you provide a detailed explanation?


 ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(1);
        ExecutorHandler handler = new ExecutorHandler(executor);
        gifDrawable = new GifDrawableBuilder().taskExecutor(executor).from(source).build();

**Comment by koral--** [comment] 2023-05-23 14:20
`source` is `resoruces, R.mimpap.<id>` in your case.
Instead of using XML, associate the drawable with view in the code:
`gifImageView.setImageDrawable(gifDrawable)`

**Comment by mshandan** [comment] 2023-05-23 14:31
Okay, where should I control the changes in gif frames?  I tried to add logic to modify gif frames in ExecutorHandler, but it doesn't seem to change the playback of gifs?

**Comment by koral--** [comment] 2023-05-23 14:39
I've deleted a duplicated comment.
You don't have to add any logic to modify frames.
Here are the only modifications: https://github.com/mshandan/demo/compare/main...koral--:demo:main

**Comment by mshandan** [comment] 2023-05-23 14:51
Sorry, it's possible that I didn't describe my problem clearly. I now need to implement a function that changes the display of gif based on a parameter. If the value is large, the gif will play to the back, and if the value is small, the gif will fall back to the front. In short, gif has 60 frames. When my parameter is 5, frame 5 is displayed, and when my parameter is 40, frame 40 is displayed.

**Comment by mshandan** [comment] 2023-05-23 14:52
使用ExecutorHandler我感觉到gif的播放确实非常流畅了，但是这个并不是我需要的功能，非常可惜。

**Comment by mshandan** [comment] 2023-05-23 14:52
Using ExecutorHandler, I feel that the playback of gif is indeed very smooth, but this is not the feature I need, which is very regrettable.

**Comment by koral--** [comment] 2023-05-23 16:34
Ok now it seems I understand. I'm afraid you can't achieve smoother seeking using this library. The frames of a gif can contain only a difference between the actual frames which user sees. So in order to render the 100th frame it may be needed to render all the 99 frames before.

**Comment by koral--** [comment] 2023-05-27 00:55
I'm closing this issue as it seems to be answered, but you can still comment if needed.

**Closed as completed by koral--** 2023-05-27 00:55 UTC
