### ISSUE TITLE
it can't be works From XML

### ISSUE THREAD

**Issue by tyl210110** [koral--/android-gif-drawable#184] opened 2015-07-02 08:42 UTC
It works nomal from code,but it focus closed when it from XML！I want know why and what make it happened this ?

**Comment by koral--** [comment] 2015-07-02 19:33
Please post complete stacktrace and your XML.

**Comment by tyl210110** [comment] 2015-07-06 02:07
![001](https://cloud.githubusercontent.com/assets/5423204/8514635/9170ca94-23c6-11e5-8a8c-490de6e6d5c4.png)
![002](https://cloud.githubusercontent.com/assets/5423204/8514636/9e2d809c-23c6-11e5-9768-a4d926bcf57c.png)
![004](https://cloud.githubusercontent.com/assets/5423204/8514641/ab6d9ddc-23c6-11e5-8970-d6f629844ed9.png)

**Comment by nuddlesW** [comment] 2015-07-06 09:09
I encounter the same problem, i am using it in the listView ,are there ways to solve it ?

**Comment by tyl210110** [comment] 2015-07-06 09:11
There has no way to solve it present .

**Comment by koral--** [comment] 2015-07-06 17:37
It looks like duplicate of #170. You need to add manually styleable if you are using eclipse.

**Closed by koral--** 2015-07-06 17:37 UTC

**Comment by tyl210110** [comment] 2015-07-07 01:14
![qq 20150707091054](https://cloud.githubusercontent.com/assets/5423204/8536769/231143cc-2488-11e5-8463-a6144de01dbd.png)
I has add it,but it still not working

**Comment by koral--** [comment] 2015-07-07 09:38
That XML must be located in project which package name in manifest is `pl.droidsonroids.gif` https://github.com/koral--/android-gif-drawable/issues/170#issuecomment-105498028
Is it true in your `GifTest` project?

**Comment by tyl210110** [comment] 2015-07-07 09:42
Zhe packageName must be pl.droidsonroids.gif ? If this it has not a good expansion.

**Comment by koral--** [comment] 2015-07-07 15:28
Requirement is that package name in AndroidManifest in project which mentioned XML is located in must match that defined in java code.

I think the best way to achieve that in Eclipse is to create library project with library sources and that XML and add that project as a reference to application project.

**Comment by tyl210110** [comment] 2015-07-08 01:42
Is there has other solution to it ?

**Comment by tyl210110** [comment] 2015-07-08 01:46
I want to use it in my project but it is not perfect From xml. I‘m so sed for it.

**Comment by koral--** [comment] 2015-07-08 15:52
The easiest way is to use gradle/android studio instead of eclipse, everything works out of the box there.

Another solution: assuming that `GifTest` is your application project and you have library sources inside and required XML added, you can change import of R to match your package name from AndroidManifest.xml.

**Comment by tyl210110** [comment] 2015-07-09 01:37
Thank you very much.

**Comment by koral--** [comment] 2015-09-08 11:09
How to for eclipse: https://github.com/koral--/android-gif-drawable-eclipse-sample

**Comment by tyl210110** [comment] 2015-09-08 11:57
Thank you very much.
