### ISSUE TITLE
 UI thread stucks when I create GifDrawable(byteBuffer ByteBuffer)

### ISSUE THREAD

**Issue by DFGDEN** [koral--/android-gif-drawable#685] opened 2019-09-04 19:35 UTC
I use text with a lot of(30+ items) ImageSpans with gifs. And UI thread stucks about 200-300ms when I create GifDrawables. Can you fix it? For example using optional placeholder.

**Comment by koral--** [comment] 2019-09-06 15:34
Could you paste your code related to this issue?

**Comment by koral--** [comment] 2019-10-05 17:46
Closing due to lack of steps to reproduce.

**Closed by koral--** 2019-10-05 17:46 UTC
Labels: needs info
