### ISSUE TITLE
(Android 5.0)Gif drawable issues

### ISSUE THREAD

**Issue by JunbinLu** [koral--/android-gif-drawable#168] opened 2015-05-24 06:45 UTC
when Gif drawable  is running on Android 5.0,it have an error occurred.

Error:
 invalid address or address of corrupt block 0xab13462c passed to dlfree
Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadbaad in tid 12339

**Comment by lindesu** [comment] 2015-05-24 07:05
I have the same error. Will it happen in 64-bit android? Google issue Android 5.0 is base on 64-bit systems

**Comment by koral--** [comment] 2015-05-24 10:35
Could you post native stacktrace (like there: https://github.com/koral--/android-gif-drawable/issues/12#issue-22711043)?

**Comment by nuoyan2** [comment] 2015-06-04 11:27
I also met in 5.0 can not run the bug and the landlord to solve the same problem Not print any abnormal information to print as same as the original poster   Hope koral can solve soon

**Comment by koral--** [comment] 2015-06-05 00:50
I need complete stacktrace and/or info how to reproduce that error, without that I don't know what to do.

**Comment by nuoyan2** [comment] 2015-06-05 02:05
I don't have the print information report any unusual exception information I send you the past in the form of photos ，You can test in 5.0 I am a Chinese English is not very good, please forgive me is to rely on translation software，I don't know how to reply the picture, I'll give you a handwritten copy down bugs are as follows:
    PID(10513)   TID(10513)  Application (com.example.gif)  Tag(libc)           Text:      Fatak signal 11 (SIGSEGV), code 2, fault addr 0xafb00000 int tip 10513 (com.example.gif)
PID(5101)   TID(5137)  Application (com.example.gifview)  Tag(OpenGLRrenderer)          Text: SFEffectCache:clear() , mSize = 0  
The above is red warning message I only keep the picture before copying Please forgive me。

**Comment by JunbinLu** [comment] 2015-06-05 02:16
My problem has been solved, you can look issus #170 that is closed ..You  can  try it.

**Comment by nuoyan2** [comment] 2015-06-05 02:47
(≧﹏ ≦)Thank you my English is not good time I see a little bit of translation

**Comment by nuoyan2** [comment] 2015-06-11 11:44
I hope I can send a moderator eclipse version of the demo I believe using eclipse or a lot of thank you very much

**Comment by nuoyan2** [comment] 2015-06-17 10:20
12 days I haven't done... What I use is koral release last year so don't support 5.0 trouble LuJunBin hair inside the eclipse examples have java8 abnormality is as follows:
06-17 18:13:10.036: E/AndroidRuntime(1861): FATAL EXCEPTION: main
06-17 18:13:10.036: E/AndroidRuntime(1861): Process: pl.droidsonroids.gif, PID: 1861
06-17 18:13:10.036: E/AndroidRuntime(1861): java.lang.RuntimeException: Unable to start activity ComponentInfo{pl.droidsonroids.gif/main.MainActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class pl.droidsonroids.gif.GifImageView
Thank you very much

**Comment by koral--** [comment] 2015-06-17 11:28
With eclipse you need to `attrs` to `res/values`, like described here: https://github.com/koral--/android-gif-drawable/issues/170#issuecomment-105498028

**Comment by nuoyan2** [comment] 2015-06-17 11:31
my attrs.xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <declare-styleable name="GifTextureView">
        <attr name="gifSource" format="reference|string"/>
        <attr name="isOpaque" format="boolean"/>
    </declare-styleable>
    <declare-styleable name="GifView">
        <attr name="freezesAnimation" format="boolean"/>
    </declare-styleable>
</resources>

**Comment by koral--** [comment] 2015-06-17 11:34
It should look like this: https://github.com/koral--/android-gif-drawable/blob/master/src/main/res/values/attrs.xml

**Comment by nuoyan2** [comment] 2015-06-17 11:34
Before I use is that you take the class.jar Last year the jar of the engineering project due to personal technology problems now can't transfer the eclipse, all want to seek an eclipse project thank you very much

**Comment by nuoyan2** [comment] 2015-06-17 11:37
I see just now I found my attrs is the same as you

**Comment by koral--** [comment] 2015-06-21 00:48
@nuoyan2 do you still have a problem?

**Comment by nuoyan2** [comment] 2015-06-21 09:55
I'm sorry, bother you rest, yes there is still a problem, I don't technology can I use your aar. Jar you seems can only use in the studio tools. I consult a friend with the studio, he technology is much but he take you for give me the APP still 5.0 collapse directly, after 5.0 below. More than 95% in China or in eclipse I sincerely hope you can release a version of the eclipse. Thanks.

**Comment by koral--** [comment] 2015-06-21 13:22
OK, there is another issue for eclipse support (#177). I am closing this one due to lack of information from the author of first post.

**Closed by koral--** 2015-06-21 13:22 UTC
Labels: bug, incomplete

**Comment by nuoyan2** [comment] 2015-06-21 13:41
Thank you very much.

**Comment by LuckLe** [comment] 2015-08-18 08:57
JunbinLu  你是怎么解决5.0版本崩溃问题的？ how do you solve the problem in 5.0?

**Comment by yuanfangCBC** [comment] 2015-08-28 09:05
LuckLe , I also met the same problem,could you tell me how do you solve?

**Comment by LuckLe** [comment] 2015-08-31 02:28
sorry，i do not solve the problem. my friends say the reason may be the .so, there is not  x64

**Comment by nuoyan2** [comment] 2015-08-31 02:49
I have already solved the problem, need demo friend can talk private QQ519719668. Email don't know why to go out, may be because the Chinese wall of the original, I only have the eclipse version of the demo

**Comment by LuckLe** [comment] 2015-08-31 03:32
thanks nuoyan2 , his demo starts work. i hope we can communicate with each other and to help more people.

**Comment by koral--** [comment] 2015-08-31 15:55
@nuoyan2 @LuckLe if you have working eclipse demo, you can share it and I can add/link to it in README

**Comment by nuoyan2** [comment] 2015-09-01 05:50
@koral-- I'm very sorry, I also want to share with you, but I won't be making the upload file, all got this morning didn't do well, you can add me if you can QQ519719668 I give you the source code, you come to share, after all, this is the demo you wrote I just use it, I will upload to infringe your rights. You can also tell your email, but I don't know that I can send in the past, after all, China has a limit.

**Comment by nuoyan2** [comment] 2015-09-01 05:57
@koral--     http://yunpan.cn/cmurzRdY2Y98v     Access to the password： de1b      This is the cloud disk 360 share connection and access password, you can try to open

**Comment by nuoyan2** [comment] 2015-09-02 01:47
@koral-- I share your demo to Csdn connection address：http://download.csdn.net/detail/qq_25342167/9072431

**Comment by koral--** [comment] 2015-09-04 15:08
@nuoyan2 I was able to download rar from the first link. I'll upload it to github ASAP.

**Comment by koral--** [comment] 2015-09-07 18:32
@nuoyan2 done: https://github.com/koral--/android-gif-drawable-eclipse-sample

**Comment by nuoyan2** [comment] 2015-09-30 05:54
I'm very sorry, I have something ask for leave before, come back and continue to look for a job, thank you very much for let me learn knowledge.

**Comment by nuoyan2** [comment] 2015-09-30 05:55
@koral-- I'm very sorry, I have something ask for leave before, come back and continue to look for a job, thank you very much for let me learn knowledge.
