### ISSUE TITLE
Animation is not playing after returning from another activity. 

### ISSUE THREAD

**Issue by alla-dubovska** [koral--/android-gif-drawable#660] opened 2019-05-20 07:37 UTC
I use `GifTextureView` to display animation from file like this:

`readmojiView.setInputSource(InputSource.FileSource(file))`

But when open a new ativity and then return back to first one animation view is empty.

**Comment by koral--** [comment] 2019-09-01 14:09
Sorry for the long delay, but I could not reproduce that.
Could provide a complete sample project which reproduces this issue?

**Comment by koral--** [comment] 2019-10-05 17:46
Closing due to lack of steps to reproduce.

**Closed by koral--** 2019-10-05 17:46 UTC
Labels: needs info
