### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by RandomAltThing** [koral--/android-gif-drawable#169] opened 2015-05-25 15:53 UTC
I am creating a windows 8 launcher and I have an animated GIF with the windows loading logo. It didn't crash before I added this code.

<b>Main.xml</b>

<pre><?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:gravity="center"
    android:orientation="vertical" >

    <pl.droidsonroids.gif.GifImageView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/background1"
    android:src="@drawable/windows_loading"
    />

</LinearLayout>
</pre>

**Comment by RandomAltThing** [comment] 2015-05-25 15:54
Apparently <pre> isint working for me. Here is main.xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:gravity="center"
    android:orientation="vertical" >

    <pl.droidsonroids.gif.GifImageView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/background1"
    android:src="@drawable/windows_loading"
    />

</LinearLayout>

**Comment by RandomAltThing** [comment] 2015-05-25 15:54
Sorry, it got messed up ^^

**Comment by koral--** [comment] 2015-05-25 16:00
Please post a stacktrace.

**Comment by RandomAltThing** [comment] 2015-05-25 16:02
Like a CatLog?

**Comment by RandomAltThing** [comment] 2015-05-25 16:02
LogCat*

**Comment by koral--** [comment] 2015-05-25 16:58
Yes. Optionally you can say how you to create such launcher so I could try to reproduce that.

**Comment by koral--** [comment] 2015-06-21 00:48
Closing due to incompletion, may be reopened if more information is provided.

**Closed by koral--** 2015-06-21 00:48 UTC
Labels: incomplete
