### ISSUE TITLE
Crash in Android-6.0.1

### ISSUE THREAD

**Issue by liuyx** [koral--/android-gif-drawable#547] opened 2018-05-15 10:08 UTC
hi, I encounter a crash in android-6.0.1 from Java call 
synchronized long renderFrame(Bitmap frameBuffer) {
        return renderFrame(this.gifInfoPtr, frameBuffer);
 }
renderFrame is a native call, the Native crash stack is below:
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 97427de4
  r0 97427de4  r1 ffffffff  r2 00003f03  r3 0000ac50
  r4 825afe80  r5 00000000  r6 8f35900c  r7 8f358370
  r8 00003033  r9 82a29ef0  10 00003f03  fp 97427de4
  ip 0000007d  sp 8f358340  lr 970c8b91  pc 970cb85c  cpsr 20070010
    #00  pc 0000585c  /data/app/com.alibaba.android.rimet-1/lib/arm/libpl_droidsonroids_gif.so
    #01  lr 00002b91  /data/app/com.alibaba.android.rimet-1/lib/arm/libpl_droidsonroids_gif.so
    --- --- ---
    00 pc 0000585c  /data/app/com.alibaba.android.rimet-1/lib/arm/libpl_droidsonroids_gif.so

After disassembly the so, I find out that the real crash method is in 
MEMSET_ARGB

It may be the stack:
MEMSET_ARGB
disposeFrameIfNeeded
drawNextBitmap
getBitmaps
Java_pl_droidsonroids_gif_GifInfoHandle_renderFrame

**Comment by koral--** [comment] 2018-05-21 22:50
Thanks for the report I'll check that.

**Comment by liuyx** [comment] 2018-05-22 03:29
It crashed at NEON instructions.

**Comment by koral--** [comment] 2018-05-22 07:37
Was it on device without NEON support?

**Comment by liuyx** [comment] 2018-05-22 08:06
It's not like that. All the crashed devices is just below:
android 7.1.1  6 phones
6.0.1 1 phone
5.1 1 phone
5.1.1 1 phone
7.1.2 1 phone

**Comment by koral--** [comment] 2018-05-22 08:57
OK, thanks.

**Comment by koral--** [comment] 2018-07-09 00:28
Sorry for the long delay.
Do you know steps to reproduce?

**Comment by liuyx** [comment] 2018-07-12 08:50
I don't know how to reproduce it either, it's reported at online monitor.

**Comment by koral--** [comment] 2018-08-13 01:25
Which library version have you used?

**Comment by koral--** [comment] 2018-08-26 01:58
Currently there is no NEON instructions: https://github.com/koral--/android-gif-drawable/commit/d675ccc9af9b708ab024084697a3b2211addfac2

Not sure if that was a reason, however I could not reproduce this issue. So I'm closing this ticket. It can be reopened if more info is provided.

**Closed by koral--** 2018-08-26 01:58 UTC
Labels: bug
