### ISSUE TITLE
play 2 or more gif files one after another in single imageview container.

### ISSUE THREAD

**Issue by csmuthukuda** [koral--/android-gif-drawable#477] opened 2017-11-15 08:10 UTC
hello @koral-- ,I am trying to implement this behavior to a list of gifs to play one after another as a sequence video.I have used code from [here](https://github.com/koral--/android-gif-drawable/commit/d8fa54f625ba99215034804f2527e3cbfdd130f1) as you explained,but for some reason the animation getting stuck after few frames in first child .After doing some logging and debugging i have found out that the programme is not going forward after draw method. any help appreciate..

**Comment by csmuthukuda** [comment] 2017-11-15 12:21
Oh..thnx for the quick reply.Im really sitting duck in here without knowing how to do this.eagerly waiting for your kind reply..👍👍

**Comment by csmuthukuda** [comment] 2017-11-17 01:55
hey @koral-- any luck with it yet..

**Comment by koral--** [comment] 2017-11-17 10:33
Sorry for the slowness, I'll try to check this within few days.

**Comment by csmuthukuda** [comment] 2017-11-17 10:54
Ah never mind koral-- take your time..👍👍

**Comment by wantitmore** [comment] 2017-11-19 08:49
I also come across the problem. a group of gif play one by one.but be stuck in one gif drawable. It occurs in some moments,but not happen frequently.

**Comment by koral--** [comment] 2017-11-21 01:16
@csmuthukuda @wantitmore I need  more information about your cases. 
Which Android version you are using?
Are your ImageViews located inside ListView or RecyclerView? Are they always visible?
Ideally if you can share snippet of code which reproduces the issue.

**Comment by wantitmore** [comment] 2017-11-21 02:05
@koral--  my fault I think. now the bug I has fixed. : )

**Comment by csmuthukuda** [comment] 2017-11-21 13:58
hello @koral-- i am using api 23 marshmellows and i am not using any list view or any other dynamic view its just an static image view.and this the code I have extracted from your examples..


  ` 
 public static class ChainedGifDrawable extends Drawable implements AnimationListener
 {

    private final pl.droidsonroids.gif.GifDrawable[] mDrawables;
    private int mCurrentIndex;

    public ChainedGifDrawable(List<pl.droidsonroids.gif.GifDrawable> drawables) {
        mDrawables = drawables.toArray(new pl.droidsonroids.gif.GifDrawable[0]);

        for (pl.droidsonroids.gif.GifDrawable drawable : drawables) {
            drawable.addAnimationListener(this);

        }
    }

    @Override
    public void onAnimationCompleted(int loopNumber) {
        Log.e("Called ","Checked");
        mCurrentIndex++;
        mCurrentIndex %= mDrawables.length;
        mDrawables[mCurrentIndex].setCallback(getCallback());
        mDrawables[mCurrentIndex].invalidateSelf();
    }

    @Override
    public void invalidateSelf() {
        mDrawables[mCurrentIndex].invalidateSelf();
        Log.e("Called invalidateSelf "+mCurrentIndex ,"Checked");
    }

    @Override
    public void scheduleSelf(@NonNull Runnable what, long when) {
        mDrawables[mCurrentIndex].scheduleSelf(what, when);
        Log.e("Called scheduleSelf "+mCurrentIndex ,"Checked");
    }

    @Override
    public void unscheduleSelf(@NonNull Runnable what) {
        mDrawables[mCurrentIndex].unscheduleSelf(what);
        Log.e("Called unscheduleSelf "+mCurrentIndex ,"Checked");
    }

    @Override
    public int getIntrinsicWidth() {
        Log.e("Called getIntrinsicWidth "+mCurrentIndex ,"Checked");
        return mDrawables[mCurrentIndex].getIntrinsicWidth();
    }

    @Override
    public int getIntrinsicHeight() {
        Log.e("Called getIntrinsicHeight "+mCurrentIndex ,"Checked");
        return mDrawables[mCurrentIndex].getIntrinsicHeight();
    }

    @Override
    protected void onBoundsChange(Rect bounds) {
        for (pl.droidsonroids.gif.GifDrawable drawable : mDrawables) {
            drawable.setBounds(bounds);
        }
        Log.e("Called onboundsChange "+mCurrentIndex ,"Checked");
    }


    @Override
    public void draw(@NonNull Canvas canvas) {
        mDrawables[mCurrentIndex].draw(canvas);
        Log.e("Called draw "+mCurrentIndex ,"Checked");
    }

    @Override
    public void setAlpha(@IntRange(from = 0, to = 255) int alpha) {
        for (pl.droidsonroids.gif.GifDrawable drawable : mDrawables) {
            drawable.setAlpha(alpha);
        }
        Log.e("Called setAlpha "+mCurrentIndex ,"Checked");
    }

    @Override
    public void setColorFilter(@Nullable ColorFilter colorFilter) {
        for (pl.droidsonroids.gif.GifDrawable drawable : mDrawables) {
            drawable.setColorFilter(colorFilter);
        }
        Log.e("Called setcolorfilter "+mCurrentIndex ,"Checked");
    }

    @Override
    public int getOpacity() {
        Log.e("Called getOpacity  "+mCurrentIndex ,"Checked");
        return PixelFormat.TRANSLUCENT;
    }

    public void setAnimationEnabled() {

        mDrawables[0].setCallback(getCallback());
    }
}`

**Comment by Bendor** [comment] 2017-11-21 14:20
The same problem for me on android api >= 23

**Comment by koral--** [comment] 2017-11-22 02:31
@Bendor @csmuthukuda Could you create a sample project with minimum amount of code which reproduces this issue?

**Comment by csmuthukuda** [comment] 2017-11-24 03:51
hey @koral--  I have created a sample project to reproduce the issue.Check this out..[https://github.com/csmuthukuda/ChainDrawableDemo.git](url)

**Comment by Bendor** [comment] 2017-11-24 10:21
Hi @koral-- 
I have another case (maybe it does not relate to this bug). Please see my example:
`
import static android.view.Gravity.CENTER_HORIZONTAL;
import static android.view.ViewGroup.LayoutParams.MATCH_PARENT;
import static android.view.ViewGroup.LayoutParams.WRAP_CONTENT;

public class MainActivity extends AppCompatActivity {

    private LinearLayout rootLayout;
    private GifDrawable gifDrawable;
    private ImageView gifImageOne;
    private ImageView gifImageTwo;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        rootLayout = new LinearLayout(this);
        rootLayout.setOrientation(LinearLayout.VERTICAL);
        rootLayout.setGravity(CENTER_HORIZONTAL);

        Button btChangeGif = new Button(this);
        btChangeGif.setText("load gifs");
        btChangeGif.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                loadGifs();
            }
        });
        addView(btChangeGif, WRAP_CONTENT);

        Button btResetGifGif = new Button(this);
        btResetGifGif.setText("change second gif");
        btResetGifGif.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                changeSecondGif();
            }
        });
        addView(btResetGifGif, WRAP_CONTENT);

        gifImageOne = new ImageView(this);
        gifImageOne.setAdjustViewBounds(true);
        addView(gifImageOne, MATCH_PARENT);

        gifImageTwo = new ImageView(this);
        gifImageTwo.setAdjustViewBounds(true);
        addView(gifImageTwo, MATCH_PARENT);

        addContentView(rootLayout, new LinearLayout.LayoutParams(
                MATCH_PARENT,
                MATCH_PARENT));

    }

    private void addView(View view, int width) {
        rootLayout.addView(view, new LinearLayout.LayoutParams(
                width,
                WRAP_CONTENT));
    }

    private void loadGifs() {
        GifDrawable gifDrawable = getGifSample();
        MultiCallback multiCallback = new MultiCallback();
        gifImageOne.setImageDrawable(gifDrawable);
        multiCallback.addView(gifImageOne);

        gifImageTwo.setImageDrawable(gifDrawable);
        multiCallback.addView(gifImageTwo);
        gifDrawable.setCallback(multiCallback);
    }

    private void changeSecondGif() {
        if (gifDrawable.getCallback() instanceof MultiCallback) {
            MultiCallback mc = (MultiCallback) gifDrawable.getCallback();
            mc.removeView(gifImageTwo); //remove second view
        }

        /**
         * load different gif. But the same problem will be if we call  gifImageTwo.setImageDrawable(null)
         */
        GifDrawable newGifDrawable = loadGif("gif_sample2.gif");

        /**
         * Set new gif. This call will stuck first gif animation.
         *  But the same problem will be if we call  'gifImageTwo.setImageDrawable(null)' or  'gifImageTwo.setImageBitmap(...)' etc
         *
         */
        gifImageTwo.setImageDrawable(newGifDrawable);

        /**
         * gifDrawable.start(), gifDrawable.reset() etc. not help
         */
    }

    private GifDrawable getGifSample() {
        if (gifDrawable == null) {
            gifDrawable = loadGif("gif_sample.gif");
        }
        return gifDrawable;
    }

    private GifDrawable loadGif(String assetName) {
        GifDrawableBuilder gifBuilder = new GifDrawableBuilder();
        try {
            return gifBuilder.from(getAssets(), assetName).build();
        } catch (IOException e) {
            Log.e("MainActivity", "loadGif error", e);
        }
        return null;
    }
}
`
As I found out the problem is that:
When we set new Drawable (or bitmap or icon, uri...) to ImageView then ImageView call method
 'android.widget.ImageView#updateDrawable'  that set 'mDrawable.setCallback(null);' and our GifDrowable lost callbak.
See 'android.widget.ImageView#setImageDrawable' and  'android.widget.ImageView#updateDrawable'

**Comment by Bendor** [comment] 2017-11-24 10:29
The difficulty is that 'android.graphics.drawable.Drawable#setCallback' is final method and also we can't change 'ImageView.updateDrawable' behavior.
For myself, I fix it as follows:
`public class GifImageView extends AppCompatImageView {

    @Nullable
    private GifDrawable mCurrentGifDrawable;
    @Nullable
    private MultiCallback mCurrentGifMultiCallback;

    public GifImageView(Context context) {
        super(context);
    }

    public GifImageView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public GifImageView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    @Override
    public void setImageResource(int resId) {
        setGifDrawable(null);
        super.setImageResource(resId);
    }

    @Override
    public void setImageBitmap(Bitmap bm) {
        setGifDrawable(null);
        super.setImageBitmap(bm);
    }

    @Override
    public void setImageIcon(@Nullable Icon icon) {
        setGifDrawable(null);
        super.setImageIcon(icon);
    }

    @Override
    public void setImageURI(@Nullable Uri uri) {
        setGifDrawable(null);
        super.setImageURI(uri);
    }

    @Override
    public void setImageDrawable(@Nullable Drawable newDrawable) {
        if (newDrawable instanceof GifDrawable) {
            setGifDrawable((GifDrawable) newDrawable);
        } else {
            setNonGifDrawable(newDrawable);
        }
    }

    private void setNonGifDrawable(Drawable newDrawable) {
        setGifDrawable(null);
        if (newDrawable != null) {
            super.setImageDrawable(newDrawable);
        }
    }

    private void setGifDrawable(@Nullable GifDrawable newGifDrawable) {
        if (newGifDrawable == mCurrentGifDrawable) {
            return; //early exit
        }
        GifDrawable previousGifDrawable = mCurrentGifDrawable;
        MultiCallback previousGifMultiCallback = mCurrentGifMultiCallback;

        Drawable.Callback originalCallback = newGifDrawable != null ? newGifDrawable.getCallback() : null;

        /**When we set new drawable to ImageView then our MultiCallback callback in gif drawable will be reset ot null (see android.widget.ImageView#updateDrawable)
         * This leads to gif animation getting stuck.
         * To fix it we hold current gif and after call 'super.setImageDrawable(Drawable drawable) we need set to this gif MultiCallback which was lost
         */
        super.setImageDrawable(newGifDrawable);

        if (previousGifDrawable != null) {
            previousGifMultiCallback.removeView(this);
            //reset callback to gif that has been changed after call super.setImageDrawable(..)
            previousGifDrawable.setCallback(previousGifMultiCallback);
        }

        mCurrentGifDrawable = newGifDrawable;
        if (mCurrentGifDrawable != null) {
            if (originalCallback instanceof MultiCallback) {
                mCurrentGifMultiCallback = ((MultiCallback) originalCallback);
            } else {
                mCurrentGifMultiCallback = new MultiCallback();
                if (originalCallback != null && originalCallback != this) {
                    mCurrentGifMultiCallback.addView(originalCallback);
                }
            }

            mCurrentGifMultiCallback.addView(this);
            //we have to set MultiCallback to new GifDrawable because afer call
            mCurrentGifDrawable.setCallback(mCurrentGifMultiCallback);
        } else {
            mCurrentGifMultiCallback = null;
        }
    }
}`

Maybe you'll find better solution

**Comment by koral--** [comment] 2017-11-25 23:57
@csmuthukuda look here: https://github.com/koral--/android-gif-drawable/commit/d8fa54f625ba99215034804f2527e3cbfdd130f1#diff-d9f40f3b1ffabd2faa7c3df1f8a2859fR29
There is no equivalent in your code.

**Comment by csmuthukuda** [comment] 2017-11-26 01:00
Can you please explain what do you mean my there is no equivalent @koral-- ..is something missing in my sample project..if it is can you highlight them in here please..

**Comment by koral--** [comment] 2017-11-26 01:12
@Bendor I'm not sure what effect do you want to achieve but if you want to associate the same drawable instance with more than one view you need to use MultiCallback or similar solution.

I'll close this thread since it is not an issue with library. But feel free to add more comments.

**Closed by koral--** 2017-11-26 01:12 UTC
Labels: question

**Comment by koral--** [comment] 2017-11-26 01:13
@csmuthukuda 
You need to subclass `ImageView` and override `verifyDrawable` method. Like this:
```
@Override
 			protected boolean verifyDrawable(@NonNull Drawable dr) {
 				super.verifyDrawable(dr);
 				return true;
			}
```

**Comment by csmuthukuda** [comment] 2017-11-26 01:20
@koral--  So you mean in order to run this i should have place the image view in a fragment.actually can you make it work as it is in my sample project without using a fragment behavior..

**Comment by koral--** [comment] 2017-11-26 01:28
Sure, look here: https://github.com/csmuthukuda/ChainDrawableDemo/pull/1

**Comment by csmuthukuda** [comment] 2017-11-26 02:06
OMG..man you are the savior man..thanx thanx a lot for everything @koral--
