### ISSUE TITLE
Run Android  5.1  Crash

### ISSUE THREAD

**Issue by CaesarZhao** [koral--/android-gif-drawable#171] opened 2015-05-26 03:32 UTC
Hi   koral:

05-26 11:25:48.188: E/AndroidRuntime(30343): FATAL EXCEPTION: main
05-26 11:25:48.188: E/AndroidRuntime(30343): Process: com.example.testgif, PID: 30343
05-26 11:25:48.188: E/AndroidRuntime(30343): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testgif/com.example.testgif.MainActivity}: android.view.InflateException: Binary XML file line #13: Error inflating class pl.droidsonroids.gif.GifTextView
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.os.Looper.loop(Looper.java:135)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at java.lang.reflect.Method.invoke(Native Method)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
05-26 11:25:48.188: E/AndroidRuntime(30343): Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class pl.droidsonroids.gif.GifTextView
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.app.Activity.setContentView(Activity.java:2145)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at com.example.testgif.MainActivity.onCreate(MainActivity.java:13)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.app.Activity.performCreate(Activity.java:5990)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	... 10 more
05-26 11:25:48.188: E/AndroidRuntime(30343): Caused by: java.lang.reflect.InvocationTargetException
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at java.lang.reflect.Constructor.newInstance(Native Method)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	... 21 more
05-26 11:25:48.188: E/AndroidRuntime(30343): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lpl/droidsonroids/gif/R$styleable;
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at pl.droidsonroids.gif.GifViewUtils.isFreezingAnimation(GifViewUtils.java:66)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at pl.droidsonroids.gif.GifTextView.init(GifTextView.java:112)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at pl.droidsonroids.gif.GifTextView.<init>(GifTextView.java:44)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	... 24 more
05-26 11:25:48.188: E/AndroidRuntime(30343): Caused by: java.lang.ClassNotFoundException: Didn't find class "pl.droidsonroids.gif.R$styleable" on path: DexPathList[[zip file "/data/app/com.example.testgif-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.testgif-2/lib/arm, /vendor/lib, /system/lib]]
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-26 11:25:48.188: E/AndroidRuntime(30343): 	... 27 more
05-26 11:25:48.188: E/AndroidRuntime(30343): 	Suppressed: java.lang.ClassNotFoundException: pl.droidsonroids.gif.R$styleable
05-26 11:25:48.188: E/AndroidRuntime(30343): 		at java.lang.Class.classForName(Native Method)
05-26 11:25:48.188: E/AndroidRuntime(30343): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-26 11:25:48.188: E/AndroidRuntime(30343): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-26 11:25:48.188: E/AndroidRuntime(30343): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-26 11:25:48.188: E/AndroidRuntime(30343): 		... 28 more
05-26 11:25:48.188: E/AndroidRuntime(30343): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

XML  FILE:

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:gravity="center"
     >
     
    <TextView android:layout_height="wrap_content"
        android:layout_width="wrap_content"
        android:text="gif动画兼容测试 "/>
    
    <pl.droidsonroids.gif.GifTextView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/gif_emoticon_01"
    />
    
</LinearLayout>

I need you help !  Thanks very much!

**Comment by koral--** [comment] 2015-05-26 09:41
Duplicate of #170

**Closed by koral--** 2015-05-26 09:41 UTC
