### ISSUE TITLE
 Is not compatible with Android 6.0 ？

### ISSUE THREAD

**Issue by MrTrying** [koral--/android-gif-drawable#285] opened 2016-04-25 13:12 UTC
```
GifDrawable gifFromStream = null;
try {
	InputStream is = (InputStream) msg;
	BufferedInputStream bis = new BufferedInputStream(is);
	gifFromStream = new GifDrawable(bis);
} catch (IOException e) {
	e.printStackTrace();
}
gifFromStream.start();
gitImageView.setImageDrawable(gifFromStream);
```
Using the above code on Android 5.0 is normal, but it will use Ben collapse on Android 6.0.
The msg instanceof FileInputStream.

**Comment by koral--** [comment] 2016-04-25 14:53
No, everything should work on Android 6.0.

**Comment by MrTrying** [comment] 2016-04-26 02:03
```
GifDrawable gifFromStream = null;
try {
	InputStream is = (InputStream) msg;
	BufferedInputStream bis = new BufferedInputStream(is);
	gifFromStream = new GifDrawable(bis);
} catch (IOException e) {
	e.printStackTrace();
}
gifFromStream.start();
gitImageView.setImageDrawable(gifFromStream);
```
Using the above code on Android 5.0 is normal, but it will use Ben collapse on Android 6.0.
The msg instanceof FileInputStream.

**Comment by koral--** [comment] 2016-04-26 11:17
OK, I'll check this.

**Comment by koral--** [comment] 2016-04-27 02:18
I have 2 questions?
1. Does `msg` contain only GIF or there is something else before?
2. Does the problem persist if buffer in `BufferedInputStream` is large enough to hold whole GIF (second parameter in constructor is a size)?

**Comment by MrTrying** [comment] 2016-04-27 07:05
Only in gif form FileInputStream.
The BufferedInputStream using the default size.
`public static final int DEFAULT_BUFFER_SIZE = 8192;`

**Comment by koral--** [comment] 2016-04-27 23:08
Error "GifError 104: No screen descriptor detected" means that GIF header could not be read successfully eg. source `InputStream` has been closed or something else is reading from it at the same time.
I could not reproduce this issue on Android 6.0. using code from your snippet. There should be nothing in library related to reading `InputStream`s which works differently on Android 6.0.
If you are not closing underlying `InputStream` nor affect it in other way and its content is the same on all android versions please complete sample which reproduces this issue including GIF.

PS buffer size must be large enough to hold all GIF file contents excluding header
PPS if you have a `FileInputStream` obtained from `File`, path you can create `GifDrawable` directly from it without `InputStream`.

**Comment by MrTrying** [comment] 2016-04-28 06:33
I understand. I will save Gif locally, and then directly use the path of the file to create GifDrawable.
```
GifDrawable gifDrawable = null;
try {
	gifDrawable = new GifDrawable(path);
} catch (IOException e) {
	e.printStackTrace();
}
gifDrawable.start();
gifimageView.setImageDrawable(gifDrawable);
```
So there is no problem.

**Closed** 2016-04-28 11:25 UTC
Labels: can't reproduce, needs info
