### ISSUE TITLE
[HELP] Gif very thin using wrap content

### ISSUE THREAD

**Issue by p4ulor** [koral--/android-gif-drawable#793] opened 2022-03-22 13:34 UTC
# Hey,
## I'm trying to use your widget on a dialog, but wrap_content isn't working for me. It appears very thin like this:
![image](https://user-images.githubusercontent.com/32241574/159492144-dffa3a53-06a4-41f3-8020-e4a0ffbde7c2.png)
## Only when I set a height or width it works, like this:
![image](https://user-images.githubusercontent.com/32241574/159492338-9b156676-81db-4bed-8f82-8cd9264043f4.png)

## Can you help me on how to keep the original ratio of the image, so that it doesn't look stretch out and looks good? Thanks!
Sorry I'm a beginner

**Comment by koral--** [comment] 2022-03-28 00:34
Is behavior the same if you use an `ImageView` instead of `GifImageView`?

**Comment by p4ulor** [comment] 2022-03-28 14:10
By setting to ImageView the gif doesn't play as expected (with layout_height="300dp"):
![image](https://user-images.githubusercontent.com/32241574/160416465-832258db-f014-49f7-b9e5-cb87d2c06aac.png)
With wrap content it doesnt appear (very thin) like in the first image I showed on this issue. It's all in my public repo if you wanna try it out 😔

**Comment by koral--** [comment] 2022-03-28 14:49
By the same behavior, I meant measurement.
Ofc ImageView does not support animated GIFs OOTB.

If wrap_content is ignored in the same way on both views then the cause is not located in this library but somewhere else in your code.

Does it reproduce in a very minimal project? I mean an empty Activity with only dialog, which layout consists only of ImageView, without any external dependencies?

**Comment by p4ulor** [comment] 2022-03-28 15:39
I removed the CardView and now the wrap_content works 👍
![image](https://user-images.githubusercontent.com/32241574/160434991-1d780b73-cc97-4f99-acc7-5052afbaa5cb.png)
I'll try to use other ways to host the GifImageView and the rest of some other Views in the Dialog
thanks :]

**Comment by koral--** [comment] 2022-03-28 16:08
ok, good to hear.
I'm closing this issue since it is not a bug in the library.

**Closed as completed by koral--** 2022-03-28 16:08 UTC
