### ISSUE TITLE
Couldn't load pl_droidsonroids_gif: findLibrary returned null 	at java.lang.Runtime.loadLibrary(Runtime.java:365) 	at java.lang.System.loadLibrary(System.java:535) 	at pl.droidsonroids.gif.GifInfoHandle.<clinit>(Unknown Source)

### ISSUE THREAD

**Issue by kaka2009** [koral--/android-gif-drawable#235] opened 2015-12-14 03:19 UTC
in some device （not all），error ：Caused by: java.lang.UnsatisfiedLinkError: Couldn't load pl_droidsonroids_gif: findLibrary returned null
	at java.lang.Runtime.loadLibrary(Runtime.java:365)
	at java.lang.System.loadLibrary(System.java:535)
	at pl.droidsonroids.gif.GifInfoHandle.<clinit>(Unknown Source)

how to solve it？

**Comment by koral--** [comment] 2015-12-14 13:06
It looks like you are not using current library version (1.1.11). See also https://github.com/koral--/android-gif-drawable#upgrading-from-1110.

Issue is a duplicate of: https://github.com/koral--/android-gif-drawable/issues/51

**Closed by koral--** 2015-12-14 13:06 UTC
Labels: duplicate
