### ISSUE TITLE
Canvas: trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by tianxia--** [koral--/android-gif-drawable#808] opened 2022-09-15 11:20 UTC
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@422a755
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:87)
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:264)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:97)
	at pl.droidsonroids.gif.GifDrawable.draw(SourceFile:4)
	at android.widget.ImageView.onDraw(ImageView.java:1462)
	at android.view.View.draw(View.java:23898)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.draw(View.java:23901)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at com.blue.baseui.widget.InterceptLinearLayout.dispatchDraw(SourceFile:3)

**Comment by koral--** [comment] 2022-09-15 13:48
Attach the code which reproduces your issue.

**Comment by koral--** [comment] 2023-01-16 14:10
Closing due to lack of repro steps.

**Closed as completed by koral--** 2023-01-16 14:10 UTC
Labels: needs info
