### ISSUE TITLE
native crash when feeding a malformed gif file

### ISSUE THREAD

**Issue by rakex** [koral--/android-gif-drawable#141] opened 2015-03-31 08:40 UTC
check the following file.
![aaa](https://cloud.githubusercontent.com/assets/292025/6915182/8e8b2f20-d7c4-11e4-99e3-db152b55adb7.gif)

**Comment by koral--** [comment] 2015-03-31 12:12
I could not reproduce crash with the current library version. Decoding error occurs and animation is restarted. It looks like this is fixed in #80.

**Closed by koral--** 2015-03-31 12:12 UTC
Labels: bug, duplicate
