### ISSUE TITLE
Add details to exception messages eg. "Too many open files" to "GifError 101: Failed to open given input"

### ISSUE THREAD

**Issue by manoj99** [koral--/android-gif-drawable#340] opened 2016-09-10 06:03 UTC
Im try to fetch gif from asset folder but it was throwing me "GifError 101: Failed to open given input" error.
There is almost 4K number of gifs in assets folder. some are showing me fine but after some time it was  not loading and throwing me like this error.
/_here is assets Dir structure
assets->asset_goods-->{gif images.}
*/
/_code snippet*/
try{
 d = new GifDrawable(context.getAssets(), "asset_goods/1.gif");
 } catch (IOException e) {
}

**Comment by koral--** [comment] 2016-09-10 15:07
Does that error happen for random files (given file sometimes is opened and sometimes doesn't) or always for the same files (in given app installation)?
Do you open a lot of files at the same time in your app? Each `GifDrawable` instance created from asset requires also 1 open file descriptor.

I'll try to reproduce that but for now with details you provided the most probable reason is that the limit of per-process open files has been exceeded, AFAIK it is approx 1000-2000.

Additionally I can add more precise error messages to error 101.

**Comment by koral--** [comment] 2016-09-11 02:45
I've extended `GifIOException` message by native errno description. Library with this extension is available in OSS snapshot repo (`1.2.3-SNAPSHOT`).
Exception message will look like this, eg. in case of open files limit exceeded: `GifError 101: Failed to open given input Too many open files`.
Let me know what is the second part in your case.

**Comment by manoj99** [comment] 2016-09-12 05:45
yes i am doing to fetch  too many file at same time. is any solution for that so  i can manually close already opened file?or any alternative solution for the same.

**Comment by koral--** [comment] 2016-09-12 14:36
The fastest solution is probably to call `GifDrawable#recycle()` as soon as given instance is no longer needed, it will close underlying file descriptor. This is called automatically by finalizer but you can call it earlier yourself. 

Other solution is to read asset to buffer (`byte[]` or `ByteBuffer`) you will need more heap space but less open file descriptors.

Generally (applicable also to another places in your code) you can ensure that file descriptors are closed as soon as possible and there is no missing `.close()`/`.recycle()` or similar method calls. Assets, `FileInput`/`OutputStream` etc. all of these use file descriptors at the low level.

Another option (workaround rather than solution) is to divide app to several processes (via `android:process` attribute in manifest) - open files limit is tied to process, not the whole app, but that may cause a lot of work and unintended side effects.

So the only thing I can do on library side is to add more verbose error messages. I'm changing this issue status from bug to feature-request.

**Comment by koral--** [comment] 2016-11-13 03:14
Done, available in version `1.2.4-SNAPSHOT`

**Closed by koral--** 2016-11-13 03:14 UTC
Labels: feature-request
