### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/user/0/com.meizu.setup/app_lib/libpl_droidsonroids_gif.so1.1.16" is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by godguy213** [koral--/android-gif-drawable#319] opened 2016-07-20 09:06 UTC
hi,I use this lib to display my gif.But I meet the UnsatisfiedLinkError error sometimes when I install my apk on samsung device. Is anyone know why? thanks.

**Comment by koral--** [comment] 2016-07-20 12:04
What is device model?

**Comment by godguy213** [comment] 2016-07-21 02:56
hi,It's MEIZU PRO5 which use samsung CPU 7420. thanks.

**Comment by godguy213** [comment] 2016-07-22 04:07
hi, koral,How can I avoid this error?Any suggesstion?

**Comment by koral--** [comment] 2016-07-22 11:19
This error is related to #51 - filename `libpl_droidsonroids_gif.so1.1.16` can be produced only if normal loading has failed.
Doing a clean app install may be a workaround.
Could you post a stacktrace?

**Comment by koral--** [comment] 2016-07-23 20:48
I was unable to reproduce this error but potential fix has been just pushed in version `1.1.18-SNAPSHOT`.

**Comment by godguy213** [comment] 2016-07-25 02:43
ok,I will try the 1.1.18 version to see if this error can produce again.thanks for helping. The stacktrace below:

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/user/0/com.meizu.setup/app_lib/libpl_droidsonroids_gif.so1.1.16" is 64-bit instead of 32-bit
    at java.lang.Runtime.load(Runtime.java:331)
    at java.lang.System.load(System.java:981)
    at avn.a(SourceFile:61)
    at avk.a(SourceFile:58)
    at pl.droidsonroids.gif.GifInfoHandle.<clinit>(SourceFile:30)
    at aut.<init>(SourceFile:160)
    at aut.<init>(SourceFile:110)
    at com.meizu.setup.activity.FlymeAccountRecommendActivity.b(SourceFile:255)
    at com.meizu.setup.activity.FlymeAccountRecommendActivity.D(SourceFile:247)
    at com.meizu.setup.activity.FlymeAccountRecommendActivity.E(SourceFile:288)
    at com.meizu.setup.activity.FlymeAccountRecommendActivity.B(SourceFile:114)
    at com.meizu.setup.activity.FlymeAccountRecommendActivity.onCreate(SourceFile:106)
    at android.app.Activity.performCreate(Activity.java:6074)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1117)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2452)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2566)
    at android.app.ActivityThread.access$800(ActivityThread.java:158)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5506)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)

**Comment by godguy213** [comment] 2016-07-25 02:58
How can i use the version 1.1.18, I change the dependencies below, but the android studio failed to reslove pl.droidsonroids.gif:android-gif-drawable:1.1.18.
dependencies {
   compile 'pl.droidsonroids.gif:android-gif-drawable:1.1.18'
}

**Comment by koral--** [comment] 2016-07-25 11:29
You need to add oss snapshot repository and `-SNAPSHOT` suffix to version name. Here are instructions: https://github.com/koral--/android-gif-drawable#gradle-snapshot-repository

**Comment by koral--** [comment] 2016-08-18 01:13
Closing due to inactivity, but potential fix is included in `1.2.0`.

**Closed by koral--** 2016-08-18 01:13 UTC
Labels: bug
