### ISSUE TITLE
gifimageView leak file descriptors

### ISSUE THREAD

**Issue by liuq315** [koral--/android-gif-drawable#504] opened 2018-01-15 11:40 UTC
i use android-gif-drawable to display gif image,  
in my layout, i use a RelativeLayout contain pl.droidsonroids.gif.GifImageView, 
this view shows gif image and png image placed in res/drawable-ldpi,  when i exit my app, i found this view will hold a file descriptor in /proc/$(process id)/fd every time, eventually this will lead to crash

// java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
//      at android.view.InputChannel.nativeReadFromParcel(Native Method)
//      at android.view.InputChannel.readFromParcel(InputChannel.java:148)
//      at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:690)
//      at android.view.ViewRootImpl.setView(ViewRootImpl.java:499)

my platform is android 4.4

**Comment by koral--** [comment] 2018-01-21 03:09
I think it is not a bug. 
`GifImageView` with GIF file added from XML holds a `GifDrawable` instance which holds open file descriptor. When `GifDrawable` is recycled (which is triggered by finalizer) file descriptor will be closed.
It is not defined when exactly finalizer will be invoked just like garbage collector.
You can force garbage collection from profiler in Android Studio. If there are no strong references to `GifImageView`s the file descriptors should be closed.

If you have a lot of `GifImageView`s and can really reach the limit of open file descriptors you can for example recycle `GifDrawable`s manually or buffer resources to byte arrays or direct byte buffers.

I'll close this issue as not a bug. However, feel free to comment.

**Closed by koral--** 2018-01-21 03:09 UTC
Labels: bug
