### ISSUE TITLE
SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by Carlos2927** [koral--/android-gif-drawable#658] opened 2019-05-13 11:26 UTC
![图片](https://user-images.githubusercontent.com/12493233/57617819-4729de00-75b4-11e9-9e66-fe723b51656b.png)
![图片](https://user-images.githubusercontent.com/12493233/57617928-8eb06a00-75b4-11e9-8748-540f92cce0e1.png)
三星 SM G965U  Android 9,level 28
android-gif-drawable version: 1.2.16

**Comment by Carlos2927** [comment] 2019-05-13 11:35
![gif_notification_setting_samsung](https://user-images.githubusercontent.com/12493233/57618519-442fed00-75b6-11e9-838d-e6818bf029fc.gif)

**Comment by Carlos2927** [comment] 2019-05-13 11:36
@koral--

**Comment by koral--** [comment] 2019-09-01 15:49
Sorry for the delay, but I could not reproduce this issue on devices I have access to.
Could you share a minimal complete project which can reproduce this issue?

**Comment by koral--** [comment] 2019-10-05 17:46
Closing due to lack of steps to reproduce.

**Closed by koral--** 2019-10-05 17:46 UTC
Labels: bug, can't reproduce, needs info
